### ISSUE TITLE
Your description

### ISSUE THREAD

**Issue by tbrsvn** [heimskr/heimskr#1]
This is not an issue I just wanted to get in touch with you! What is that weird symbol string that's your company in the description of you and how did you make it? It is very interesting.

**Comment by heimskr** [comment]
[b̴̭̰̟̟͕e͙͢h̛̤̹͈o̬͓l̴̩ḓ̺̝̹̖͎ ̩̝͚̘̬̗̘t͔̩̲̦̙̳͕hḛ͢ ̹̺̗̲͡v̖̟̙̺̻o̬͇̝i̤̩d̗̲͙̭͠](http://eeemo.net/)

**Comment by tbrsvn** [comment]
Thank you so much eeemo.net is really cool
